/* Contexto del portafolio inyectado al modelo. Sin RAG: el dataset es pequeño y fijo. */
export const PROFILE = {
  es: [
    "PERFIL",
    "- Gustavo Maldonado es Security AI/ML Engineer en Ciudad de México, México.",
    "- 17+ años en infraestructura TI (500+ equipos Windows, Linux y macOS).",
    "- Portafolio respaldado por 1,200+ tests automatizados.",
    "",
    "ESPECIALIDADES",
    "- Caza de amenazas con memoria episódica (Pantheon).",
    "- Pentesting autónomo con auditoría inmutable (Ares).",
    "- Detección de anomalías en grafos financieros (Helix).",
    "- IA generativa: RAG, agentes LangGraph, Tool Calling, MCP.",
    "",
    "STACK TÉCNICO",
    "- IA Generativa y LLMs: LLM, RAG, CRAG, LangGraph, LangChain, OpenAI, Claude, Gemini, Ollama, Qdrant, ChromaDB, Tool Calling, Prompt Engineering, MCP Server.",
    "- ML, NLP y Grafos: Python 3.12, PyTorch, scikit-learn, LightGBM, K-Means, Isolation Forest, GNN (S3), Anomaly Detection, NLP, MLflow.",
    "- Ciberseguridad: Threat Hunting, Pentesting, Purple Team, eJPTv2, SIEM Splunk, Bandit SAST, NIST AC-6, ATT&CK, DevSecOps.",
    "- Cloud y DevOps: GCP Vertex AI, AWS S3, Terraform, Docker, Kubernetes, GitHub Actions, Prometheus, Grafana, FastAPI, PostgreSQL, Redis.",
    "",
    "PROYECTOS PRINCIPALES",
    "1. Pantheon v2.1 (Threat Hunting): plataforma autónoma de caza de amenazas con memoria episódica y scoring online. 397 tests, 0 fallos. Agente de investigación CRAG (Hermes) con LLM local, GFCN AttractorIndex en espacio 8D (Laser & Gravitational Score) sin reentrenamiento. Actualización automática desde Ares (loop purple team). Fail-closed por diseño, human-in-the-loop, audit trail con cadena de hashes. Stack: Python, FastAPI, LangGraph, Ollama, PostgreSQL, Prometheus, ATT&CK, Docker.",
    "2. Ares v3.2 (Pentesting): asistente de hacker ético con memoria episódica y auditoría inmutable. 555+ tests. Reconocimiento autónomo con triaje ML, sandbox Docker aislado, gate de aprobación para acciones de alto riesgo y algoritmo Vulcan IDA* (Iterative Deepening A*) para la secuencia de explotación de mínimo CCI. Auditoría inmutable con hash encadenado SHA-256 y réplica opcional en S3 WORM. MCP Server (7 herramientas) y Purple Bridge bidireccional con Pantheon. Stack: Python 3.12, LangGraph, Ollama, ML, Docker, MCP, S3 WORM.",
    "3. Helix (Graph ML): detección de anomalías en grafos sobre la esfera cuaterniónica S3 para fraude financiero. AUC 0.9647 (AMLSim). Cada nodo recibe una rotación en S3; los nodos ilícitos generan patrones geométricos distinguibles. Selección automática de modelo (Helix/SAGE/GCN/MLP) por densidad del grafo. NEXUS y SONAR: scoring semi-supervisado que propaga riesgo desde semillas confirmadas sin reentrenamiento. AUC 0.9624 (Elliptic), 0.9565 (PaySim), 0.8899 (NF-UQ-NIDS). Stack: Python, PyTorch, scikit-learn, S3, ChebyshevFNO, GraphSAGE/GCN.",
    "",
    "OTROS PROYECTOS",
    "- Momus: agente de detección de vulnerabilidades en APIs. 6/6 en benchmark vs 0/6 manual.",
    "- Fraud Sentinel: detección de fraude en siniestros con agentes LangGraph + LightGBM. ROC-AUC 0.81.",
    "- Credit Behavior Engine: scoring crediticio conductual neuro-simbólico. AUROC 0.9958.",
    "- Smart Onboarding CV: onboarding bancario con visión (MobileNetV2) + scoring + reglas. F1 0.93.",
    "- ACO Route Optimizer: optimización de rutas de última milla con Ant Colony Optimization. +13.75%.",
    "- NEURAL-RMF: alerta temprana de crisis epilépticas focales (ventana promedio de 47 min antes de la crisis).",
    "- EQ-RMF: detección temprana de sismos, investigación colaborativa con el NIED de Japón.",
    "",
    "LOGROS Y CERTIFICACIONES",
    "- Especialista en Infraestructura TI en Creative Service desde Jun 2009 (17 años, 500+ endpoints).",
    "- Colaboración de investigación con el NIED de Japón (EQ-RMF).",
    "- Investigación propia: NEURAL-RMF.",
    "- 1,200+ tests automatizados (Ares 555+, Pantheon 397, Helix 67, Momus 163).",
    "- Certificación eJPTv2 (hacking ético).",
    "- Data Science - TripleTen.",
    "- Google Cybersecurity Professional.",
    "- AWS Cloud Practitioner - 2026 (en curso).",
    "",
    "MÉTRICAS DESTACADAS",
    "- 17+ años en infraestructura TI.",
    "- 1,200+ tests automatizados.",
    "- 6/6 detección en benchmark Momus.",
    "- 47 min de alerta temprana (NEURAL-RMF).",
    "",
    "CONTACTO",
    "- Correo: gustavo.a.maldonado.v@gmail.com",
    "- Teléfono: +52 55 4130 8278",
    "- GitHub: https://github.com/Gusmal02",
    "- LinkedIn: https://linkedin.com/in/gustavomaldonadov"
  ].join("\n"),

  en: [
    "PROFILE",
    "- Gustavo Maldonado is a Security AI/ML Engineer in Mexico City, Mexico.",
    "- 17+ years in IT infrastructure (500+ Windows, Linux, and macOS endpoints).",
    "- Portfolio backed by 1,200+ automated tests.",
    "",
    "SPECIALTIES",
    "- Threat hunting with episodic memory (Pantheon).",
    "- Autonomous pentesting with immutable audit trails (Ares).",
    "- Anomaly detection on financial graphs (Helix).",
    "- Generative AI: RAG, LangGraph agents, Tool Calling, MCP.",
    "",
    "TECHNICAL STACK",
    "- Generative AI & LLMs: LLM, RAG, CRAG, LangGraph, LangChain, OpenAI, Claude, Gemini, Ollama, Qdrant, ChromaDB, Tool Calling, Prompt Engineering, MCP Server.",
    "- ML, NLP & Graphs: Python 3.12, PyTorch, scikit-learn, LightGBM, K-Means, Isolation Forest, GNN (S3), Anomaly Detection, NLP, MLflow.",
    "- Cybersecurity: Threat Hunting, Pentesting, Purple Team, eJPTv2, SIEM Splunk, Bandit SAST, NIST AC-6, ATT&CK, DevSecOps.",
    "- Cloud & DevOps: GCP Vertex AI, AWS S3, Terraform, Docker, Kubernetes, GitHub Actions, Prometheus, Grafana, FastAPI, PostgreSQL, Redis.",
    "",
    "MAIN PROJECTS",
    "1. Pantheon v2.1 (Threat Hunting): autonomous threat hunting platform with episodic memory and online scoring. 397 tests, 0 failures. CRAG investigation agent (Hermes) with a local LLM, online GFCN AttractorIndex in 8D space (Laser & Gravitational Score) with no retraining. Automatic updates from Ares closing the purple-team loop. Fail-closed by design, human-in-the-loop, hash-chained audit trail. Stack: Python, FastAPI, LangGraph, Ollama, PostgreSQL, Prometheus, ATT&CK, Docker.",
    "2. Ares v3.2 (Pentesting): ethical hacking assistant with episodic memory and immutable audit trails. 555+ tests. Autonomous reconnaissance with ML triage, isolated Docker sandbox, approval gate for high-risk actions, and Vulcan IDA* (Iterative Deepening A*) for the minimum accumulated-CCI exploitation sequence. Immutable audit trail with SHA-256 chained hashes and optional S3 WORM replication. MCP Server (7 tools) and a bidirectional Purple Bridge with Pantheon. Stack: Python 3.12, LangGraph, Ollama, ML, Docker, MCP, S3 WORM.",
    "3. Helix (Graph ML): graph anomaly detection over the unit quaternion sphere S3 for financial fraud. AUC 0.9647 (AMLSim). Each node receives a rotation in S3; illicit nodes generate distinguishable geometric patterns. Automatic model selection (Helix/SAGE/GCN/MLP) based on graph density. NEXUS and SONAR: semi-supervised scorers that propagate risk from confirmed seeds without retraining. AUC 0.9624 (Elliptic), 0.9565 (PaySim), 0.8899 (NF-UQ-NIDS). Stack: Python, PyTorch, scikit-learn, S3, ChebyshevFNO, GraphSAGE/GCN.",
    "",
    "OTHER PROJECTS",
    "- Momus: API vulnerability detection agent. 6/6 in benchmark vs 0/6 manual.",
    "- Fraud Sentinel: insurance claim fraud detection with LangGraph agents + LightGBM. ROC-AUC 0.81.",
    "- Credit Behavior Engine: neuro-symbolic behavioral credit scoring. AUROC 0.9958.",
    "- Smart Onboarding CV: banking onboarding with vision (MobileNetV2) + scoring + rules. F1 0.93.",
    "- ACO Route Optimizer: last-mile route optimization with Ant Colony Optimization. +13.75%.",
    "- NEURAL-RMF: early warning for focal epileptic crises (average 47-minute window before onset).",
    "- EQ-RMF: early earthquake detection, collaborative research with NIED (Japan).",
    "",
    "MILESTONES & CERTIFICATIONS",
    "- IT Infrastructure Specialist at Creative Service since Jun 2009 (17 years, 500+ endpoints).",
    "- Research collaboration with NIED (Japan) - EQ-RMF.",
    "- Own research: NEURAL-RMF.",
    "- 1,200+ automated tests (Ares 555+, Pantheon 397, Helix 67, Momus 163).",
    "- eJPTv2 certification (ethical hacking).",
    "- Data Science - TripleTen.",
    "- Google Cybersecurity Professional.",
    "- AWS Cloud Practitioner - 2026 (in progress).",
    "",
    "KEY METRICS",
    "- 17+ years in IT infrastructure.",
    "- 1,200+ automated tests.",
    "- 6/6 detection in the Momus benchmark.",
    "- 47 min early warning (NEURAL-RMF).",
    "",
    "CONTACT",
    "- Email: gustavo.a.maldonado.v@gmail.com",
    "- Phone: +52 55 4130 8278",
    "- GitHub: https://github.com/Gusmal02",
    "- LinkedIn: https://linkedin.com/in/gustavomaldonadov"
  ].join("\n")
};